export const MATERIAS_FOBAM = [
    "Apreciación Musical 1",
    "Apreciación Musical 2",
    "Canto 1",
    "Canto 2",
    "Canto 3",
    "Canto 4",
    "Canto 5",
    "Canto Popular 1",
    "Canto Popular 2",
    "Canto Popular 3",
    "Canto Popular 4",
    "Canto Popular 5",
    "Coro 1",
    "Coro 2",
    "Danzas Folklóricas",
    "Dicción Alemana 1",
    "Dicción Alemana 2",
    "Dicción Inglesa 1",
    "Dicción Inglesa 2",
    "Dicción Italiana 1",
    "Dicción Italiana 2",
    "Dicción Portuguesa 1",
    "Dicción Portuguesa 2",
    "Didáctica Especializada",
    "Didáctica General",
    "Educación Vocal",
    "Ensamble 1",
    "Ensamble 2",
    "Ensamble 3",
    "Ensamble 4",
    "Entrenamiento Escénico",
    "Expresión Corporal",
    "Instrumento Fundamental 1: Arpa",
    "Instrumento Fundamental 1: Bajo Eléctrico",
    "Instrumento Fundamental 1: Bandoneón",
    "Instrumento Fundamental 1: Batería",
    "Instrumento Fundamental 1: Clarinete",
    "Instrumento Fundamental 1: Contrabajo",
    "Instrumento Fundamental 1: Corno",
    "Instrumento Fundamental 1: Flauta Dulce",
    "Instrumento Fundamental 1: Flauta Traversa",
    "Instrumento Fundamental 1: Guitarra Clásica",
    "Instrumento Fundamental 1: Guitarra Eléctrica",
    "Instrumento Fundamental 1: Guitarra Popular",
    "Instrumento Fundamental 1: Oboe",
    "Instrumento Fundamental 1: Percusión Académica",
    "Instrumento Fundamental 1: Percusión Folklórica",
    "Instrumento Fundamental 1: Piano",
    "Instrumento Fundamental 1: Saxo",
    "Instrumento Fundamental 1: Sikus-Quena",
    "Instrumento Fundamental 1: Trombón",
    "Instrumento Fundamental 1: Trompeta",
    "Instrumento Fundamental 1: Viola",
    "Instrumento Fundamental 1: Violín",
    "Instrumento Fundamental 1: Violoncello",
    "Instrumento Fundamental 2: Arpa",
    "Instrumento Fundamental 2: Bajo Eléctrico",
    "Instrumento Fundamental 2: Bandoneón",
    "Instrumento Fundamental 2: Batería",
    "Instrumento Fundamental 2: Clarinete",
    "Instrumento Fundamental 2: Contrabajo",
    "Instrumento Fundamental 2: Corno",
    "Instrumento Fundamental 2: Flauta Dulce",
    "Instrumento Fundamental 2: Flauta Traversa",
    "Instrumento Fundamental 2: Guitarra Clásica",
    "Instrumento Fundamental 2: Guitarra Eléctrica",
    "Instrumento Fundamental 2: Guitarra Popular",
    "Instrumento Fundamental 2: Oboe",
    "Instrumento Fundamental 2: Percusión Académica",
    "Instrumento Fundamental 2: Percusión Folklórica",
    "Instrumento Fundamental 2: Piano",
    "Instrumento Fundamental 2: Saxo",
    "Instrumento Fundamental 2: Sikus-Quena",
    "Instrumento Fundamental 2: Trombón",
    "Instrumento Fundamental 2: Trompeta",
    "Instrumento Fundamental 2: Viola",
    "Instrumento Fundamental 2: Violín",
    "Instrumento Fundamental 2: Violoncello",
    "Instrumento Fundamental 3: Arpa",
    "Instrumento Fundamental 3: Bajo Eléctrico",
    "Instrumento Fundamental 3: Bandoneón",
    "Instrumento Fundamental 3: Batería",
    "Instrumento Fundamental 3: Clarinete",
    "Instrumento Fundamental 3: Contrabajo",
    "Instrumento Fundamental 3: Corno",
    "Instrumento Fundamental 3: Flauta Dulce",
    "Instrumento Fundamental 3: Flauta Traversa",
    "Instrumento Fundamental 3: Guitarra Clásica",
    "Instrumento Fundamental 3: Guitarra Eléctrica",
    "Instrumento Fundamental 3: Guitarra Popular",
    "Instrumento Fundamental 3: Oboe",
    "Instrumento Fundamental 3: Percusión Académica",
    "Instrumento Fundamental 3: Percusión Folklórica",
    "Instrumento Fundamental 3: Piano",
    "Instrumento Fundamental 3: Saxo",
    "Instrumento Fundamental 3: Sikus-Quena",
    "Instrumento Fundamental 3: Trombón",
    "Instrumento Fundamental 3: Trompeta",
    "Instrumento Fundamental 3: Viola",
    "Instrumento Fundamental 3: Violín",
    "Instrumento Fundamental 3: Violoncello",
    "Instrumento Fundamental 4: Arpa",
    "Instrumento Fundamental 4: Bajo Eléctrico",
    "Instrumento Fundamental 4: Bandoneón",
    "Instrumento Fundamental 4: Batería",
    "Instrumento Fundamental 4: Clarinete",
    "Instrumento Fundamental 4: Contrabajo",
    "Instrumento Fundamental 4: Corno",
    "Instrumento Fundamental 4: Flauta Dulce",
    "Instrumento Fundamental 4: Flauta Traversa",
    "Instrumento Fundamental 4: Guitarra Clásica",
    "Instrumento Fundamental 4: Guitarra Eléctrica",
    "Instrumento Fundamental 4: Guitarra Popular",
    "Instrumento Fundamental 4: Oboe",
    "Instrumento Fundamental 4: Percusión Académica",
    "Instrumento Fundamental 4: Percusión Folklórica",
    "Instrumento Fundamental 4: Piano",
    "Instrumento Fundamental 4: Saxo",
    "Instrumento Fundamental 4: Sikus-Quena",
    "Instrumento Fundamental 4: Trombón",
    "Instrumento Fundamental 4: Trompeta",
    "Instrumento Fundamental 4: Viola",
    "Instrumento Fundamental 4: Violín",
    "Instrumento Fundamental 4: Violoncello",
    "Instrumento Fundamental 5: Arpa",
    "Instrumento Fundamental 5: Bajo Eléctrico",
    "Instrumento Fundamental 5: Bandoneón",
    "Instrumento Fundamental 5: Batería",
    "Instrumento Fundamental 5: Clarinete",
    "Instrumento Fundamental 5: Contrabajo",
    "Instrumento Fundamental 5: Corno",
    "Instrumento Fundamental 5: Flauta Dulce",
    "Instrumento Fundamental 5: Flauta Traversa",
    "Instrumento Fundamental 5: Guitarra Clásica",
    "Instrumento Fundamental 5: Guitarra Eléctrica",
    "Instrumento Fundamental 5: Guitarra Popular",
    "Instrumento Fundamental 5: Oboe",
    "Instrumento Fundamental 5: Percusión Académica",
    "Instrumento Fundamental 5: Percusión Folklórica",
    "Instrumento Fundamental 5: Piano",
    "Instrumento Fundamental 5: Saxo",
    "Instrumento Fundamental 5: Sikus-Quena",
    "Instrumento Fundamental 5: Trombón",
    "Instrumento Fundamental 5: Trompeta",
    "Instrumento Fundamental 5: Viola",
    "Instrumento Fundamental 5: Violín",
    "Instrumento Fundamental 5: Violoncello",
    "Lenguaje Musical 1",
    "Lenguaje Musical 2",
    "Lenguaje Musical 3",
    "Lenguaje Musical 4",
    "Optativa 1",
    "Optativa 2",
    "Pedagogía General",
    "Seminario Armonía",
    "Seminario Ritmo"
];
